---
title: "quickdraw"
author: "abalamur"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F}
library(tidyverse)
library(ggplot2)
```

```{r, message = F}
humans = read_csv("https://raw.githubusercontent.com/mllewis/conceptQD/master/exploratory_analyses/2_haussdorff_distance/python_implementation/Hausdorff_Euclidean.csv")
humans.original = read_csv("https://raw.githubusercontent.com/mllewis/conceptQD/master/data/processed/human_data/conceptviz_1_by_item_data.csv")

#humans.new = rbind(humans, humans.original)
```

#Human rating vs. Hausdorff Distance
```{r}
plot(x = humans$`Hausdorff Distance`, 
     y = humans.original$human_rating_mean)
```

```{r}
plot(x = humans$`Euclidean Distance`,
     y = humans.original$human_rating_mean)

```

```{r}
ggplot(humans, aes(x = `Hausdorff Distance`, y = humans.original$human_rating_mean)) + 
  geom_point() +
  ggtitle("Hausdorff Distance") +
  geom_smooth(formula = y~  x, method = "lm")

ggplot(humans, aes(x = `Euclidean Distance`, y = humans.original$human_rating_mean)) +
  geom_point() + 
  ggtitle("Euclidean Distance") +
  geom_smooth(formula = y~  x, method = "lm")

cor(x = humans$`Hausdorff Distance`, y = humans.original$human_rating_mean)

cor(x = humans$`Euclidean Distance`, y = humans.original$human_rating_mean)
```

```{r}

ggplot(humans, aes(x = log(`Hausdorff Distance`), y = humans.original$human_rating_mean)) + 
  geom_point() +
  ggtitle("log(Hausdorff Distance)") +
  geom_smooth(formula = y ~ x, method = "lm")

ggplot(humans, aes(x = log(`Euclidean Distance`), y = humans.original$human_rating_mean)) +
  geom_point() +
  geom_smooth(formula = y~x, method = "lm") +
  ggtitle("log(Euclidean Distance")

cor(x = log(humans$`Hausdorff Distance`), y = humans.original$human_rating_mean)

cor(x = log(humans$`Euclidean Distance`), y = humans.original$human_rating_mean)
```

```{r}
summary(lm(humans.original$human_rating_mean ~ log(`Hausdorff Distance`), humans))

linear.haus = lm(humans.original$human_rating_mean ~ log(`Hausdorff Distance`), humans)
plot(linear.haus, which = 1, pch = 19)

summary(lm(humans.original$human_rating_mean ~ log(`Euclidean Distance`), humans))

linear.euc = lm(humans.original$human_rating_mean ~ log(`Euclidean Distance`), humans)
plot(linear.euc, which = 1, pch = 19)


```